export const C = {
  primary: '#e8930c',
  primaryDark: '#c57a0a',
  primaryLight: '#fdf3e1',
  hanwha: '#F37321',
  accent: '#2d2d2d',
  bg: '#f5f3ef',
  card: '#ffffff',
  border: '#e5e0d8',
  text: '#1a1a1a',
  textSub: '#6b6560',
  danger: '#d94040',
  success: '#1a8c4e',
  info: '#2b7cd4',
};

export const s = {
  header: {
    background: `linear-gradient(135deg, ${C.hanwha} 0%, ${C.primary} 50%, ${C.primaryDark} 100%)`,
    padding: '28px 24px 22px',
    color: '#fff',
  },
  headerTitle: { fontSize: 22, fontWeight: 700, letterSpacing: -0.5, color: '#fff' },
  headerSub: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 4, fontWeight: 300 },
  stepper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px 24px 16px',
    background: C.card,
    borderBottom: `1px solid ${C.border}`,
  },
  card: {
    background: C.card,
    borderRadius: 16,
    padding: '24px 20px',
    marginBottom: 16,
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
    border: `1px solid ${C.border}`,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 600,
    marginBottom: 18,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  label: { fontSize: 13, fontWeight: 600, color: C.text, marginBottom: 6, display: 'block' },
  required: { color: C.danger, marginLeft: 2 },
  input: {
    width: '100%',
    padding: '12px 14px',
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    fontSize: 15,
    background: '#fafaf8',
    color: C.text,
  },
  select: {
    width: '100%',
    padding: '12px 14px',
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    fontSize: 15,
    background: '#fafaf8',
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='12' height='8' viewBox='0 0 12 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1.5L6 6.5L11 1.5' stroke='%236b6560' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 14px center',
    cursor: 'pointer',
    color: C.text,
  },
  textarea: {
    width: '100%',
    padding: '12px 14px',
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    fontSize: 14,
    background: '#fafaf8',
    minHeight: 80,
    resize: 'vertical',
    lineHeight: 1.6,
    color: C.text,
  },
  row: { display: 'flex', gap: 12, marginBottom: 14, flexWrap: 'wrap' },
  col: { flex: 1, minWidth: 0 },
  btnPrimary: {
    width: '100%',
    padding: '14px 20px',
    background: C.primary,
    color: '#fff',
    border: 'none',
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(232,147,12,0.3)',
  },
  btnSecondary: {
    padding: '14px 20px',
    background: '#f0ece6',
    color: C.text,
    border: 'none',
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 500,
    cursor: 'pointer',
  },
  btnOutline: {
    padding: '10px 16px',
    background: 'transparent',
    color: C.primary,
    border: `2px solid ${C.primary}`,
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  tag: { display: 'inline-block', padding: '4px 10px', borderRadius: 6, fontSize: 12, fontWeight: 600 },
  hint: { fontSize: 12, color: C.textSub, marginTop: 4 },
};

export function num(v) { return Number(v) || 0; }
